### ISSUE TITLE
Start with NO_FPS instead of INTEGER_FPS

### ISSUE THREAD

**Issue by Chometh** [Rinnegatamante/Framecounter#2]
Greetings from Portugal, Rinnegatamante.

First of all, thank you so much for creating this framecounter plugin for the ps vita, I use it all the time when testing overclocks!

But there's something that kind of bothers me...

This plugin, by default, shows the "FPS: xx" overlay when a ps vita app starts running.
A lot of times, I find myself having to press and hold the START button, to turn off the overlay, every time I start a new game.

My humble request, is that you change this plugin to start with the NO_FPS enum case instead of INTEGER_FPS.

I think this is a better behaviour by default than having the overlay be visible automatically.

I tried to build my custom version of this plugin to reflect this change but I couldn't get passed the building phase with cmake and make.
I don't have much experience with building, only coding.
I even changed your code and all but couldn't end up with a .skprx file to put in my vita xD

That is all.

I wish you all the best,
- Josh Bishop

**Comment by Rinnegatamante** [comment]
[Framecounter.zip](https://github.com/Rinnegatamante/Framecounter/files/6846643/Framecounter.zip)

**Comment by Chometh** [comment]
WOW! 

I posted this issue before going to sleep and after I woke up, you had already posted a built .suprx for me!

Thank you so much for how accessible you were with me!

I already tested and it works just like I wanted it.

Again, thank you.
